### ISSUE TITLE
opening parent dir instead of files/dirs

### ISSUE THREAD

**Issue by KARTOFF8xE** [Nummer42O/nautlius-extensions#2]
When I want to open one or more files/dirs it always opens the parent dir in VSCode instead of the selected ones.

It seems that `menuProviderGetSelectedItems` builds the command correctly.

**Comment by Nummer42O** [comment]
Unable to reproduce on main branch. Please check that you are using the most recent version.
![Screenshot from 2024-11-19 16-43-29](https://github.com/user-attachments/assets/5e6da3bd-eb01-47aa-87f4-ee11a3c78977)

**Comment by KARTOFF8xE** [comment]
Got the latest Version and checked through `file --mime-type` that the type is `text/plain`.

**Comment by KARTOFF8xE** [comment]
What information would you like?

Got GNOME nautilus 42.6

**Comment by Nummer42O** [comment]
Checked on another system, getting the same error - will look into it.
